### ISSUE TITLE
Different worlds issue

### ISSUE THREAD

**Issue by Johandrex** [DogLoverPink/EssentialsX-Target-Selectors#8]
**What went wrong?**
Doesn't work with multiple words 

**Steps for recreation:**
 1. Two players go into two different worlds
 2. One try to step on a commandblocks with the command "sudo @p[r=3] sethome Parkour1"
 3. It results in the error down below, it does however work when both players are in the same world.
 
**Any errors in console? If so, post the full error here, or post it on [this](https://mclo.gs/) website and share the link.**
```
[23:39:51 ERROR]: Could not pass event ServerCommandEvent to EssentialsSelectors v1.6
java.lang.IllegalArgumentException: Cannot measure distance between Parkour4 and Parkour1
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.Location.distance(Location.java:493) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at doglover.Events.ServerCommandExecute.onConsoleCommandThingy(ServerCommandExecute.java:215) ~[EssentialsSelectors.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-131]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.Commands.dispatchServerCommand(Commands.java:247) ~[?:?]
        at net.minecraft.world.level.BaseCommandBlock.performCommand(BaseCommandBlock.java:133) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.execute(CommandBlock.java:121) ~[?:?]
        at net.minecraft.world.level.block.CommandBlock.tick(CommandBlock.java:108) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1013) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1103) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:635) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[paper-1.19.2.jar:git-Paper-131]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[paper-1.19.2.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

 
**What is your plugin, server, and java version?**
 git-Paper-131 (MC: 1.19.2)
EssentialsX Selector
1.6

**Anything else?**
I'd be super happy if it could be fixed as soon as possible :). I have like 8 worlds with hundreds of old commandblocks, they work perfectly except when players are in different worlds. Would be great if I didn't have to replace all commandblocks due to this issue.

**Comment by Johandrex** [comment]
I'll give u 10 USD if u fix it within within 2 days, rlly need it fixed asap <3

**Comment by DogLoverPink** [comment]
Yep, I'll get right on this, a very easy fix.

Thanks for reporting!

**Comment by DogLoverPink** [comment]
Should be fixed in 1.7, check releases tab :)

**Comment by Johandrex** [comment]
Awesome! Works thanks, what's your paypal? :)

**Comment by DogLoverPink** [comment]
It's all good mate, thanks for the offer though . 

A review on the spigot is always welcome though ;)
