### ISSUE TITLE
An error that occured whilst using the plugin.

### ISSUE THREAD

**Issue by RealTriassic** [DogLoverPink/EssentialsX-Target-Selectors#9]
**What went wrong?**
 An error is thrown in console when using a messaging plugin on the Bungeecord proxy. When trying to message yourself, if the plugin properly blocks this, an error will be thrown into the console of the back-end server you are on.

**Steps for recreation:**
 1. Have a messaging plugin on a Bungeecord proxy.
 2. Try to message yourself, a good messaging plugin should prevent this.
 3. The below error should occur in the console on the back-end server you are on.
 
**Any errors in console? If so, post the full error here, or post it on [this](https://mclo.gs/) website and share the link.**
```
[11:56:36 ERROR]: Could not pass event PlayerCommandPreprocessEvent to EssentialsSelectors v1.7
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.getPlugin()" because the return value of "org.bukkit.Bukkit.getPluginCommand(String)" is null
        at doglover.Events.PlayerCommandExecute.onCommandThingy(PlayerCommandExecute.java:35) ~[EssentialsSelectors-1.7.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1876]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2353) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
 
**What is your plugin, server, and java version?**
Purpur 1.19.3 b1876
EssentialsX 2.20.0-dev
EssentialsSelectors 1.7

**Comment by DogLoverPink** [comment]
Did not mean to close yet, clicked wrong button

I could not manage to test your specific case, but I do believe that it will be fixed, if it doesn't please notify me here.

**Comment by DogLoverPink** [comment]
Closing due to no response, and for the fact that it should be fixed. If you are still experiencing issues, feel free to re-open this issue.
